### ISSUE TITLE
Python client installation fails

### ISSUE THREAD

**Issue by pj7801** [cytomine/Cytomine-python-client#20]
I'm trying to install the Python client to an Ubuntu 20.04 machine with Python 2.7.18 using the instructions from here:
(https://doc.uliege.cytomine.org/pages/viewpage.action?pageId=12321357)

1. Documentation issue  
The documentation doesn't seem to be accurate:
Section 2.1
There is no "client" subdirectory in Cytomine-python-client

> cd client/
python setup.py build
python setup.py install
cd ..

2. If I run "python setup.py install" from the Cytomine-python-client directory, there are multiple errors:

**A) Syntax error in build/bdist.linux-x86_64/egg/cytomine/utilities/software.py**

>byte-compiling build/bdist.linux-x86_64/egg/cytomine/utilities/wholeslide.py to wholeslide.pyc
byte-compiling build/bdist.linux-x86_64/egg/cytomine/utilities/software.py to software.pyc
  File "build/bdist.linux-x86_64/egg/cytomine/utilities/software.py", line 85
    },
     ^
SyntaxError: invalid syntax 
byte-compiling build/bdist.linux-x86_64/egg/cytomine/utilities/__init__.py to __init__.pyc

**B) skbuild is not installed as a prerequisite by the script**

>Running opencv-python-headless-4.4.0.44/setup.py -q bdist_egg --dist-dir /tmp/easy_install-szRon7/opencv-python-headless-4.4.0.44/egg-dist-tmp-u2XlLO
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    data_files=[('', ['LICENSE', 'requirements.txt'])]
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-szRon7/opencv-python-headless-4.4.0.44/setup.py", line 9, in <module>
    # *      http://www.apache.org/licenses/LICENSE-2.0
ImportError: No module named skbuild

I found that skbuild is supposed to be in the scikit-build package, so installed it manually. Not sure if this is the right way, please confirm!

>(cytomine) cytomine@spectre:~/Cytomine/Cytomine-python-client$ pip list 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                Version            
certifi                2019.11.28         
Cytomine-Python-Client 2.2.1              
distro                 1.5.0              
joblib                 0.14.1             
mkl-fft                1.0.15             
mkl-random             1.1.0              
mkl-service            2.3.0              
numpy                  1.16.6             
olefile                0.46               
packaging              20.4               
Pillow                 6.2.1              
pip                    19.3.1             
pyparsing              2.4.7              
requests               2.24.0             
**scikit-build           0.11.1**             
scikit-learn           0.20.3             
scipy                  1.2.1              
setuptools             44.0.0.post20200106
Shapely                1.6.4.post2        
six                    1.15.0             
wheel                  0.35.1             

**C) After installing scikit-build manually, the previous error disappears, but a new one is introduced:**

>Running opencv-python-headless-4.4.0.44/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HgFGEa/opencv-python-headless-4.4.0.44/egg-dist-tmp-HrquLk
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    data_files=[('', ['LICENSE', 'requirements.txt'])]
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-HgFGEa/opencv-python-headless-4.4.0.44/setup.py", line 448, in <module>
    
  File "/tmp/easy_install-HgFGEa/opencv-python-headless-4.4.0.44/setup.py", line 99, in main
    
  File "/home/cytomine/miniconda2/envs/cytomine/lib/python2.7/re.py", line 210, in escape
    s = list(pattern)
TypeError: 'NoneType' object is not iterable

Can you please look into these?

**Comment by gvincke** [comment]
Dear @pj7801, 
The documentation you refer to is the one of the University of Liège version, that we do not support.
If your choice is to use this version of Cytomine (and its related python client), please post your issue on their own repo on [https://github.com/Cytomine-ULiege/Cytomine-python-client](https://github.com/Cytomine-ULiege/Cytomine-python-client).
To install the official Cytomine Python Client, please follow the official documentation on [https://doc.cytomine.org/Python-client](https://doc.cytomine.org/Python-client?structure=DataScientists).
Best regards.
Grégoire

**Comment by pj7801** [comment]
Hi @gvincke,

Thanks for this info. Would you please update your README.md file for the project, so it points to the right documentation? Currently it includes the link to the Uliege documentation and not the one you mentioned above. 

https://github.com/cytomine/Cytomine-python-client/blob/master/README.md

"The client is automatically installed with the Docker/Bootstrap procedure, however it is possible to install it independently on remote computers. See installation instructions here: http://doc.cytomine.be/pages/viewpage.action?pageId=12321357"

Thanks,
Patrik

**Comment by gvincke** [comment]
@pj7801 : Done !
Thanks to have pointed this out.
