### ISSUE TITLE
JSONDecodeError when Cytomine host returns a 301 http code

### ISSUE THREAD

**Issue by geektortoise** [cytomine/Cytomine-python-client#27]
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    with Cytomine(host=params.host, public_key=params.public_key, private_key=params.private_key,
  File "/usr/local/lib/python3.8/site-packages/Cytomine_Python_Client-2.2.1-py3.8.egg/cytomine/cytomine.py", line 200, in __init__
  File "/usr/local/lib/python3.8/site-packages/Cytomine_Python_Client-2.2.1-py3.8.egg/cytomine/cytomine.py", line 338, in _start
  File "/usr/local/lib/python3.8/site-packages/Cytomine_Python_Client-2.2.1-py3.8.egg/cytomine/cytomine.py", line 363, in set_current_user
  File "/usr/local/lib/python3.8/site-packages/Cytomine_Python_Client-2.2.1-py3.8.egg/cytomine/models/model.py", line 50, in fetch
  File "/usr/local/lib/python3.8/site-packages/Cytomine_Python_Client-2.2.1-py3.8.egg/cytomine/cytomine.py", line 428, in get_model
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

If I set, the redirected URL, it works. 

wanted behavior : 
Connection with the redirected URL (after 301 http code) should work

**Comment by 101x4** [comment]
I met this as well, my host is http://cytomine.domain.my. How to set the redirected URL?

**Comment by geektortoise** [comment]
@101x4 : In my case, the redirected url was httpS as http was redirected to httpS.

@chlmarchal : can you test if the problem is still there and, if it is, propose a patch ? :-) Thanks

**Comment by chlmarchal** [comment]
Fixed by [62219f7](https://github.com/cytomine/Cytomine-python-client/commit/62219f7a198b47869e19be9aa5f05d9b54475546).
