### ISSUE TITLE
[WINDOWS] locale.Error raised when using the client

### ISSUE THREAD

**Issue by waliens** [cytomine/Cytomine-python-client#3]
On Windows (10), using the client (i.e. sending request through the Cytomine object) result in this error:

```
Traceback (most recent call last):
  [...]
  File "[...]\image_adapter.py", line 60, in __init__
    self._img_instance = self._cytomine.get_image_instance(id_img_instance, include_server_urls=True)
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 452, in get_image_instance
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 123, in fetch
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 74, in __authorize
  File "[...]\miniconda\envs\cytomine\lib\locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Line 74 of cytomine.py: 
```python
locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
```

I guess it is caused by the hardcoded UNIX-like locale ? 
List of locale strings supported by windows:  https://msdn.microsoft.com/en-us/library/39cwe7zf(v=vs.100).aspx

**Comment by waliens** [comment]
The error is not raised anymore when replacing `en_US.UTF-8` with `english-us` and the client still seems to work.
