### ISSUE TITLE
Load .h5 model into algorithm

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-python-client#33]
Hi @geektortoise and Cytomine developers,

I am trying to load a Keras model into an algorithm using the following lines:

`base_path = "{}".format(os.getenv("HOME")) # Mandatory for Singularity`
        `working_path = os.path.join(base_path,str(conn.job.id))`
        `model_directory = base_path`
        `model_name = 'densenet201weights.best.h5'`
        `model = tf.keras.models.load_model(model_directory +'/'+ model_name)`

But getting the following error:

> [2021-08-04 16:16:14,931][INFO] Job (id:2722730) status update: "SavedModel file does not exist at: /home/cytomine/densenet201weights.best.h5/{saved_model.pbtxt|saved_model.pb}" (status: FAILED, progress: 1%)
[2021-08-04 16:16:14,986][INFO] [PUT] [job] 2722730 : classify_NWMS_ER_DenseNet201 (v1.0.12) : 1 | 200 OK
Traceback (most recent call last):
  File "/app/classifynwms.py", line 214, in <module>
    main(sys.argv[1:])
  File "/app/classifynwms.py", line 81, in main
    model = tf.keras.models.load_model(model_directory +'/'+ model_name)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
    meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /home/cytomine/densenet201weights.best.h5/{saved_model.pbtxt|saved_model.pb}

Please advise on how to work on this. Here's the [link to the repo](https://github.com/mizjaggy18/S_classify_NWMS_ER_DenseNet201).

**Comment by mizjaggy18** [comment]
Oh my @waliens you're my saviour! Thanks so much! It runs perfectly now :)
