### ISSUE TITLE
[WINDOWS] Dump annotations doesn't work

### ISSUE THREAD

**Issue by waliens** [cytomine/Cytomine-python-client#4]
When launching dump_annotations on a bunch of annotations, the following exceptions are raised (on each thread): 

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "[...]\cytomine\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build\bdist.win-amd64\egg\cytomine\utils.py", line 56, in run
    download_successful = self.cytomine.fetch_url_into_file(url, filename, self.override)
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 235, in fetch_url_into_file
    resp, content = self.fetch_url(url)
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 260, in fetch_url
    return self.fetch_url(resp['location'])
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 260, in fetch_url
    return self.fetch_url(resp['location'])
  File "build\bdist.win-amd64\egg\cytomine\cytomine.py", line 258, in fetch_url
    resp, content = con.request(url, headers=self.__headers)
  File "[...]\cytomine\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "[...]\cytomine\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 1412, in _request
    _updateCache(headers, response, content, self.cache, cachekey)
  File "[...]\cytomine\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 448, in _updateCache
    cache.set(cachekey, text)
  File "[...]\cytomine\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 715, in set
    f = file(cacheFullPath, "wb")
IOError: [Errno 2] No such file or directory: 'C:/[...]/desktop/tmp/cytomine/dump/.cache\\image5.cytomine.be,image,crop.png,fif=%2Fdata%2Fbeta.cytomine.be%2F18%2Fthyorid-svs%2F015-CP_11C09223_1A-2012-08-28-16.09.16.jp2&mimeType=image,jp2&topLeftX=14829&topLeftY=26959&width=63&height=62&ima,aab98d891b0257971af924f7cb56c15c'
```

Code used for dumping: 
```python
import os

from cytomine import Cytomine
from cytomine.models import Annotation

if __name__ == "__main__":
    working_path = os.path.join("c:/[...]/desktop", "tmp", "cytomine", "dump").replace("\\", "/")
    if not os.path.exists(working_path):
        os.makedirs(working_path)
    print(working_path)
    cytomine = Cytomine("beta.cytomine.be", "[...]", "[...]",
                        base_path="/api/", working_path=working_path)
    annotations = cytomine.get_annotations(716498, id_user=671279)
    dumped = cytomine.dump_annotations(
        annotations,
        get_image_url_func=Annotation.get_annotation_alpha_crop_url,
        dest_path="C:/data/cytomine/thyroid/raw",
        excluded_terms=[28792193, 15054705, 15054765, 30559888, 205806198, 22042230, 9444456]
    )
```

I have tried other locations for dumping (app data temp folder), but the same error occurs. 

It seems that httplib2 cannot create a cache file. I suspect that the exception is caused by the cache file name generated by httplib2 which might be invalid (filename might be too long, or contain invalid characters).

**Comment by waliens** [comment]
Possible solution track: http://stackoverflow.com/questions/14886640/ubuntu-encrypted-home-directory-errno-36-file-name-too-long

**Comment by waliens** [comment]
Dirty hack/workaround: disable caching in the `fetch_url` method (in `cytomine.py`) at line 255 by replacing

```python
con = httplib2.Http(self.__cache, timeout=self.__timeout) 
```
by 
```python
con = httplib2.Http(timeout=self.__timeout)    
```

**Comment by waliens** [comment]
Closent because I don’t think it is relevant anymore as it is related to the old client
